name: 'Docker Action Recipe'
description: 'Greet Someone'
inputs:
  who-to-great:
    description: 'Who to Great'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image:  'Dockerfile'
  args:
    - ${{ inputs.who-to-great }}