name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run My Own Container Action
        uses: ./
        with:
          who-to-great: '@lethisa'