name: Development in a Branch
on: [ pull_request, workflow_dispatch ]

jobs:
  debug:
    name: Debug Information
    runs-on: ubuntu-22.04
    steps:
      - name: Debug GitHub Information
        run: |
          echo "Workflow Triggered in Branch '${{ github.ref }}'"
          echo "Workflow Triggered by Event '${{ github.event_name }}'"
          echo "Workflow Triggered by Actor '${{ github.actor }}'"

  lint:
    name: Action Lint
    runs-on: ubuntu-22.04
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - run: |
          echo "::notice file=.github/workflows/DevelopInBranch.yml,line=19,col=11,endColumn=51::There is a debug message that is not always visible!"
          echo "::warning file=.github/workflows/DevelopInBranch.yml,line=19,endline=21::A lot of messages"
          echo "::error title=Script Injection,file=.github/workflows/DevelopInBranch.yml,line=13,col=37,endColumn=38::Potential script injection”
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Action Lint
        uses: devops-actions/actionlint@v0.1.3
      - name: Pull Request Title
        run: echo "PR Title is ${{ github.event.pull_request.title }}"
