name: Development in a Branch
on: [ pull_request, workflow_dispatch ]

jobs:
  debug:
    name: Debug Information
    runs-on: ubuntu-22.04
    steps:
      - name: Debug GitHub Information
        run: |
          echo "Workflow Triggered in Branch '${{ github.ref }}'"
          echo "Workflow Triggered by Event '${{ github.event_name }}'"
          echo "Workflow Triggered by Actor '${{ github.actor }}'"

  lint:
    name: Action Lint
    runs-on: ubuntu-22.04
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - run: |
          echo "::debug::This is a Debug Message"
          echo "::notice::This is a Notice Message"
          echo "::warning::This is a Warning Message"
          echo "::error::This is an Error Message"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Action Lint
        uses: devops-actions/actionlint@v0.1.3
      - name: Pull Request Title
        run: echo "PR Title is ${{ github.event.pull_request.title }}"